### ISSUE TITLE
LEDs not flashing / Wemos D1 Mini restarts when /ui/ is started in the browser

### ISSUE THREAD

**Issue by unparse** [545ch4/flippie#2]
_Disclaimer: I'm relatively new to electronics, so I guess it could also be a very easy mistake I made. But I would really appreciate some help :(_

When booting the Wemos D1 Mini the three LEDs are not flashing, but only turning off, and after they should have been flashing three times, they are turning on again.

Also when I try to go to flippie-IP in the browser, the Wemos restarts and I get this Error in the serial monitor:

```
Exception (3):
epc1=0x4020ce0c epc2=0x00000000 epc3=0x00000000 excvaddr=0x4024acbf depc=0x00000000

>>>stack>>>

ctx: cont

sp: 3ffffd00 end: 3fffffc0 offset: 01a0
3ffffea0:  4024acbf 3fff019c 3fffff10 00000001
3ffffeb0:  3fff0574 3fff019c 3fffff10 402034c7
3ffffec0:  00000000 00000000 ffffff10 4020752e
3ffffed0:  00000000 3fffdad0 3fffff10 4020758e
3ffffee0:  3ffe879b 3fff01e0 3fffff10 40207734
3ffffef0:  ffffffff 3fff01e0 3fff019c 402033a0
3fffff00:  3fff0574 3fff01e0 3fff019c 40205479
3fffff10:  2f69752f 00000000 00000000 00000000
3fffff20:  ff544820 4bc6a7f0 00006175 3ffeebec
3fffff30:  3fff01c4 3fff0250 00000001 3fff01c4
3fffff40:  00000001 3ffeebec 00000000 0000000f
3fffff50:  00000000 3fff063c 3fff019c 3ffeebec
3fffff60:  00000001 3fff01c4 3fff019c 4020567c
3fffff70:  4020a858 00000000 00001388 4020a918
3fffff80:  00000000 3fff063c feefeffe feefeffe
3fffff90:  3fffdad0 00000000 3ffeebbc 40203759
3fffffa0:  3fffdad0 00000000 3ffeebbc 402084b8
3fffffb0:  feefeffe feefeffe 3ffe850c 401004d9
<<<stack<<<

�L␀A␋␁␁��       �␌%��u�␁�␌)Q
␑Z-�Xʋ'��E␋␒��␑\��Q�    )l�5␑␁�␏␑␅␂�NRP␋JJk�A␌X-C�
Booting...
```

Following your instructions it must be something wrong with my shift registers, I guess, but I can't figure out what is wrong.. I triple checked my soldering, also under the microscope, but it seems all fine.

![IMG_6329](https://user-images.githubusercontent.com/22907213/63029824-861c4800-beb1-11e9-80a5-6f23a9e8b37c.JPG)

**Comment by 545ch4** [comment]
Sorry to hear that things didn't work as supposed :(

Have you tried to enable debugging via set ```#define DEBUG 1``` in ```src/debug.h```?

Are you attending the [CCCamp2019](https://www.ccc.de/de/updates/2019/camp-zelte)? Then we could meet in person and fix this issue.

**Comment by unparse** [comment]
Dear 545ch4, thanks so much for your fast reply! I will try enabling debugging today.

I'm not going to CCCamp (because I'm doing my bachelor thesis atm), but I really appreciate that you would take some time for me :)

**Comment by unparse** [comment]
Hi :)

When enabling the debug mode, in the serial monitor I get this:

```
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld
Booting...
.
Connected to 'wifi'
IP address: '192.168.123.134'
Finished configure flippie.
Finished defining and setting all output pins.
Fireing shift-register (enable=false, persistant=false)... xDONE.
Fireing shift-register (enable=false, persistant=false)... xDONE.
Fireing shift-register (enable=false, persistant=false)... xDONE.
Fireing shift-register (enable=false, persistant=false)... xDONE.
Fireing shift-register (enable=false, persistant=false)... xDONE.
Fireing shift-register (enable=false, persistant=false)... xDONE.

Finished first test of shift-register.
Finished initilizing flippie.
Added UIHandler
Added DotsHandler
Added PixelHandler
Added FlippieHandler
Added NotFoundHandler
Ready! Open http://192.168.123.134 in your browser
```

Are the lines `Fireing shift-register (enable=false, persistant=false)... xDONE.` supposed to say something else, when it is working?

**Comment by 545ch4** [comment]
Figured out why you got the exception: In the current version of the ESP SDK the PROGMEM string foo has changed rendering the ´.send()´ method to exit with exception. Please see my latest commit.

**Comment by unparse** [comment]
How cool! Thanks a lot! :) I just updated your firmware for the MCU and I now it forwards to /ui/ without restarting.

But still the LEDs are not flashing when resetting the D1 mini.. Though in the serial monitor it says `Fireing shift-register (enable=false, persistant=false)... xDONE.` a few times. On reset the LEDs turn off and as the first "Fireing shift-register" comes in the serial monitor, alls LEDs stay turned on again without flashing..

Can it be that they don't flash, when you bridge the current limiter with the Pads 1 and 2? Or do I have to close the ~EN_PWR connection? Also I just replaced all shift registers from the board to check if one doesn't work, but still the LEDs don't flash.

**Comment by 545ch4** [comment]
The LEDS are on the very end of the sift register. Thus, if the LED flashing is not working, it is very likely that some of the shift register is not connected properly to the next one. Check if pin 9 is connected to the following 595 pin 14.
